# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  h2:
    console:
      enabled: true

#  datasource:
#    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost/jwt
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

  kaptcha:
    properties:
      kaptcha:
        border: no
        image:
          width: 80
          height: 35
        background:
          clear:
            from: white
            to: white
        session:
          key: code
        noise:
          color: white
        textproducer:
          char:
            string: 0123456789ABCDEFGHIJKLMNPQRSTUVWXYZ
            length: 4
          font:
            names: Tahoma
            size: 30
            color: blue
        obscurificator:
          impl: com.google.code.kaptcha.impl.WaterRipple

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh


#logging:
#  level:
#    org.springframework:
#      security: DEBUG

logging:
  config: classpath:logback.xml

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: org.jozif.po
